### ISSUE TITLE
Crashing on MongoDB 4.4, possibly others

### ISSUE THREAD

**Issue by tmcallaghan** [mongodb-developer/service-tests#14]
The pre-run uploaded jstest.py is not compatible with the 4.4 branch, it fails at line 166:

class JSTestCase(interface.TestCase, interface.UndoDBUtilsMixin)

The 4.4 branch [and likely 4.2] version of interface.py does not contain class UndoDBUtilsMixin.

**Comment by craigfhoma** [comment]
Hi @tmcallaghan , thanks. The repo has been updated to support running against pre-5.0 versions.

Cheers
