### ISSUE TITLE
Docker Build Fails for MongoDB 4.4

### ISSUE THREAD

**Issue by somanipra** [mongodb-developer/service-tests#16]
Was working fine recently, suddenly started getting error. Seems like something wrong while installing cryptography in python.
................
check.warn(importable)
    copying src/cryptography/py.typed -> build/lib.linux-x86_64-cpython-37/cryptography
    creating build/lib.linux-x86_64-cpython-37/cryptography/hazmat/bindings/_rust
    copying src/cryptography/hazmat/bindings/_rust/__init__.pyi -> build/lib.linux-x86_64-cpython-37/cryptography/hazmat/bindings/_rust
    copying src/cryptography/hazmat/bindings/_rust/asn1.pyi -> build/lib.linux-x86_64-cpython-37/cryptography/hazmat/bindings/_rust
    copying src/cryptography/hazmat/bindings/_rust/ocsp.pyi -> build/lib.linux-x86_64-cpython-37/cryptography/hazmat/bindings/_rust
    copying src/cryptography/hazmat/bindings/_rust/x509.pyi -> build/lib.linux-x86_64-cpython-37/cryptography/hazmat/bindings/_rust
    running build_ext
    running build_rust
    
        =============================DEBUG ASSISTANCE=============================
        If you are seeing a compilation error please try the following steps to
        successfully install cryptography:
        1) Upgrade to the latest pip and try again. This will fix errors for most
           users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
        2) Read https://cryptography.io/en/latest/installation/ for specific
           instructions for your platform.
        3) Check our frequently asked questions for more information:
           https://cryptography.io/en/latest/faq/
        4) Ensure you have a recent Rust toolchain installed:
           https://cryptography.io/en/latest/installation/#rust
    
        Python: 3.7.3
        platform: Linux-5.4.17-2136.306.1.3.el8uek.x86_64-x86_64-with-debian-10.1
        pip: 18.1
        setuptools: 65.4.1
        setuptools_rust: 1.5.2
        =============================DEBUG ASSISTANCE=============================
    
    error: can't find Rust compiler
    
    If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.
    
    To update pip, run:
    
        pip install --upgrade pip
    
    and then retry package installation.
    
    If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.
    
    This package requires Rust >=1.41.0.
    
    ----------------------------------------

**Comment by somanipra** [comment]
workaround- updating pip in the docker
pip install --upgrade pip

**Comment by craigfhoma** [comment]
Hello, thanks for flagging this and posting a workaround. We will prioritize a fix.

**Comment by craigfhoma** [comment]
This stemmed from a permissions issue we just fixed in the Dockerfile. I just tested building an image for 4.4 with no issue.
