### ISSUE TITLE
Error during Docker Installation

### ISSUE THREAD

**Issue by vapontesmongodb** [mongodb-developer/service-tests#18]
Im getting this error trying to install docker in ubuntu :

sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get install docker git -y
sudo service docker start

$ sudo service docker start
Failed to start docker.service: Unit docker.service not found.

I solved this problem using these steps bellow:

sudo snap install docker
sudo snap services
sudo docker info

**Comment by craigfhoma** [comment]
Looking in to this with Vagner.

**Comment by craigfhoma** [comment]
Closing as this issue has been resolved.
