### ISSUE TITLE
 error: can't find Rust compiler

### ISSUE THREAD

**Issue by vapontesmongodb** [mongodb-developer/service-tests#19]
Im getting this error bellow, any idea how to fix that?

If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.
    
    This package requires Rust >=1.41.0.
    
    
   
I did the installation manual of rust before :
rustup install stable
rustup default stable
rustc --version

**Comment by craigfhoma** [comment]
Looking in to this with Vagner as well.

**Comment by craigfhoma** [comment]
Turned out that this was related to a permissions issue which we since fixed.
