### ISSUE TITLE
Error during docker build

### ISSUE THREAD

**Issue by somanipra** [mongodb-developer/service-tests#21]
Having a failure for docker build while building for 5.0 or 6.0

Below is the error 

STEP 10/16: COPY mongo /mongoShell/
Error: error building at STEP "COPY mongo /mongoShell/": checking on sources under "/service-tests/post-5.0": copier: stat: "/mongo": no such file or directory
----------------------------
Is mongo to be cloned at "/service-tests/post-5.0"folder

**Comment by craigfhoma** [comment]
Thanks, we are looking in to this.

**Comment by craigfhoma** [comment]
The work-around for this is to download the MongoDB Shell into the /post-50 directory. The shell can be downloaded from https://www.mongodb.com/try/download/shell.

Please use this method while we work on a more robust fix.
